//! Handle registries: opaque objects cross the FFI boundary as `i32` handles.
//!
//! `i32`, not `i64` — LabVIEW's Import Shared Library wizard cannot parse any
//! 64-bit integer type (see CLAUDE.md Golden Rule), and two billion handles
//! per process is far beyond any real session.
//!
//! One registry per resource type, generated by [`handle_registry!`] — the
//! pattern is 100% mechanical, which is what makes it the right place for a
//! macro. Handle `0` is reserved and never issued, so it doubles as
//! "null"/"absent". Handles are process-global and thread-safe.

use crate::error::{fail, guard, NominalErrorCode};

/// Generates a handle registry for one resource type:
/// a `Lazy<Mutex<HashMap<i32, Arc<T>>>>`, a shared `AtomicI32` counter, and
/// `insert`/`get`/`remove` functions scoped to that type.
///
/// ```ignore
/// handle_registry!(ClientHandle, nominal::core::NominalClient);
/// let h = ClientHandle::insert(client);      // -> new i32 handle (never 0)
/// let c = ClientHandle::get(h);              // -> Option<Arc<NominalClient>>
/// let existed = ClientHandle::remove(h);     // -> bool
/// ```
macro_rules! handle_registry {
    ($name:ident, $ty:ty) => {
        pub(crate) struct $name;

        impl $name {
            fn map(
            ) -> &'static std::sync::Mutex<std::collections::HashMap<i32, std::sync::Arc<$ty>>>
            {
                static MAP: once_cell::sync::Lazy<
                    std::sync::Mutex<std::collections::HashMap<i32, std::sync::Arc<$ty>>>,
                > = once_cell::sync::Lazy::new(|| {
                    std::sync::Mutex::new(std::collections::HashMap::new())
                });
                &MAP
            }

            /// Store `value` and return its new handle. Never returns 0.
            pub(crate) fn insert(value: $ty) -> i32 {
                let handle = crate::handles::next_handle();
                Self::map()
                    .lock()
                    .unwrap_or_else(|poisoned| poisoned.into_inner())
                    .insert(handle, std::sync::Arc::new(value));
                handle
            }

            /// Look up a handle. `None` if it was never issued or already freed.
            pub(crate) fn get(handle: i32) -> Option<std::sync::Arc<$ty>> {
                Self::map()
                    .lock()
                    .unwrap_or_else(|poisoned| poisoned.into_inner())
                    .get(&handle)
                    .cloned()
            }

            /// Drop the value behind `handle`. Returns whether it existed.
            pub(crate) fn remove(handle: i32) -> bool {
                Self::map()
                    .lock()
                    .unwrap_or_else(|poisoned| poisoned.into_inner())
                    .remove(&handle)
                    .is_some()
            }
        }
    };
}

/// Looks up `$handle` in `$registry`, or records an invalid-handle error and
/// returns `NominalErrorCode::InvalidHandle` from the enclosing function —
/// the prologue that starts almost every FFI function.
macro_rules! lookup_handle {
    ($registry:ty, $handle:expr) => {
        match <$registry>::get($handle) {
            Some(value) => value,
            None => {
                crate::error::set_last_error(format!(
                    "invalid {} handle: {}",
                    stringify!($registry),
                    $handle
                ));
                return crate::error::NominalErrorCode::InvalidHandle as i32;
            }
        }
    };
}

pub(crate) use {handle_registry, lookup_handle};

/// One counter shared by every registry, so a handle value can never be valid
/// in two registries at once — using an asset handle as a client handle fails
/// loudly instead of silently resolving to the wrong object.
pub(crate) fn next_handle() -> i32 {
    static NEXT: std::sync::atomic::AtomicI32 = std::sync::atomic::AtomicI32::new(1);
    NEXT.fetch_add(1, std::sync::atomic::Ordering::Relaxed)
}

// A list of handles is itself an opaque object behind a handle — this is how
// `_list`/`_search` return their results without any array or double pointer
// crossing the boundary (LabVIEW's wizard can't express either cleanly).
handle_registry!(HandleListHandle, Vec<i32>);

pub(crate) fn insert_handle_list(handles: Vec<i32>) -> i32 {
    HandleListHandle::insert(handles)
}

/// Stores the number of handles in the list in `out_count`.
#[no_mangle]
pub extern "C" fn nominal_handle_list_count(list: i32, out_count: *mut u32) -> i32 {
    guard(|| {
        let handles = lookup_handle!(HandleListHandle, list);
        if out_count.is_null() {
            return fail(NominalErrorCode::NullArgument, "out_count must not be null");
        }
        // SAFETY: out_count checked non-null above; caller owns it.
        unsafe { *out_count = handles.len() as u32 };
        0
    })
}

/// Stores the handle at `index` (0-based) in `out_handle`.
#[no_mangle]
pub extern "C" fn nominal_handle_list_get(list: i32, index: i32, out_handle: *mut i32) -> i32 {
    guard(|| {
        let handles = lookup_handle!(HandleListHandle, list);
        if out_handle.is_null() {
            return fail(
                NominalErrorCode::NullArgument,
                "out_handle must not be null",
            );
        }
        match usize::try_from(index).ok().and_then(|i| handles.get(i)) {
            Some(&handle) => {
                // SAFETY: out_handle checked non-null above; caller owns it.
                unsafe { *out_handle = handle };
                0
            }
            None => fail(
                NominalErrorCode::IndexOutOfRange,
                format!("index {index} out of range for list of {}", handles.len()),
            ),
        }
    })
}

/// Frees a handle list previously returned by a `_list`/`_search` function.
/// Frees only the list itself — the handles inside remain valid until passed
/// to their own `_free` function. Freeing twice returns an error.
#[no_mangle]
pub extern "C" fn nominal_handle_list_free(list: i32) -> i32 {
    guard(|| {
        if HandleListHandle::remove(list) {
            0
        } else {
            fail(
                NominalErrorCode::InvalidHandle,
                format!("invalid handle list: {list}"),
            )
        }
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    handle_registry!(TestHandle, String);
    handle_registry!(OtherHandle, u32);

    #[test]
    fn insert_get_remove_round_trip() {
        let handle = TestHandle::insert("hello".to_string());
        assert!(handle > 0, "handle 0 is reserved");
        assert_eq!(*TestHandle::get(handle).unwrap(), "hello");
        assert!(TestHandle::remove(handle));
        assert!(TestHandle::get(handle).is_none());
        assert!(!TestHandle::remove(handle), "double free reports false");
    }

    #[test]
    fn zero_and_unknown_handles_are_invalid() {
        assert!(TestHandle::get(0).is_none());
        assert!(TestHandle::get(-1).is_none());
        assert!(TestHandle::get(i32::MAX).is_none());
    }

    #[test]
    fn handles_are_unique_across_registries() {
        let a = TestHandle::insert("a".to_string());
        let b = OtherHandle::insert(42);
        assert_ne!(a, b);
        assert!(TestHandle::get(b).is_none(), "cross-registry use must fail");
        assert!(OtherHandle::get(a).is_none());
        assert!(!OtherHandle::remove(a), "cross-registry free must fail");
        assert!(OtherHandle::remove(b));
    }

    #[test]
    fn handle_list_round_trip() {
        let _guard = crate::error::test_message_lock();
        let list = insert_handle_list(vec![7, 8, 9]);

        let mut count = 0u32;
        assert_eq!(nominal_handle_list_count(list, &mut count), 0);
        assert_eq!(count, 3);

        let mut handle = 0i32;
        assert_eq!(nominal_handle_list_get(list, 2, &mut handle), 0);
        assert_eq!(handle, 9);

        assert_eq!(
            nominal_handle_list_get(list, 3, &mut handle),
            NominalErrorCode::IndexOutOfRange as i32
        );
        assert_eq!(
            nominal_handle_list_get(list, -1, &mut handle),
            NominalErrorCode::IndexOutOfRange as i32
        );

        assert_eq!(nominal_handle_list_free(list), 0);
        assert_eq!(
            nominal_handle_list_free(list),
            NominalErrorCode::InvalidHandle as i32
        );
        assert_eq!(
            nominal_handle_list_count(list, &mut count),
            NominalErrorCode::InvalidHandle as i32
        );
    }
}
