//! Handle registries: opaque objects cross the FFI boundary as `i32` handles.
//!
//! `i32`, not `i64` — LabVIEW's Import Shared Library wizard cannot parse any
//! 64-bit integer type (see CLAUDE.md Golden Rule), and two billion handles
//! per process is far beyond any real session.
//!
//! One registry per resource type, generated by [`handle_registry!`] — the
//! pattern is 100% mechanical, which is what makes it the right place for a
//! macro. Handle `0` is reserved and never issued, so it doubles as
//! "null"/"absent". Handles are process-global and thread-safe.

use std::os::raw::c_char;
use std::sync::Mutex;

use crate::error::{fail, guard, NominalErrorCode};
use crate::strings::{read_required_str, write_str_field};

/// One handle registry's entry in the debug directory: its type name and a
/// fn returning its currently-open handle values.
type RegistryEntry = (&'static str, fn() -> Vec<i32>);

/// Global directory of every handle registry that has ever issued a handle.
/// Populated once per registry by the `Lazy` map initializer inside
/// [`handle_registry!`], read by `nominal_debug_open_handles`. A registry
/// that was never touched is absent — it cannot have leaked anything.
static REGISTRY_DIRECTORY: once_cell::sync::Lazy<Mutex<Vec<RegistryEntry>>> =
    once_cell::sync::Lazy::new(|| Mutex::new(Vec::new()));

pub(crate) fn register_registry(name: &'static str, open_handles: fn() -> Vec<i32>) {
    REGISTRY_DIRECTORY
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner())
        .push((name, open_handles));
}

/// Generates a handle registry for one resource type:
/// a `Lazy<Mutex<HashMap<i32, Arc<T>>>>`, a shared `AtomicI32` counter, and
/// `insert`/`get`/`remove` functions scoped to that type.
///
/// ```ignore
/// handle_registry!(ClientHandle, nominal::core::NominalClient);
/// let h = ClientHandle::insert(client);      // -> new i32 handle (never 0)
/// let c = ClientHandle::get(h);              // -> Option<Arc<NominalClient>>
/// let existed = ClientHandle::remove(h);     // -> bool
/// ```
macro_rules! handle_registry {
    ($name:ident, $ty:ty) => {
        pub(crate) struct $name;

        impl $name {
            fn map(
            ) -> &'static std::sync::Mutex<std::collections::HashMap<i32, std::sync::Arc<$ty>>>
            {
                static MAP: once_cell::sync::Lazy<
                    std::sync::Mutex<std::collections::HashMap<i32, std::sync::Arc<$ty>>>,
                > = once_cell::sync::Lazy::new(|| {
                    // First touch: announce this registry to the debug
                    // directory so `nominal_debug_open_handles` covers it
                    // (no per-call cost — this closure runs exactly once).
                    crate::handles::register_registry(stringify!($name), $name::open_handles);
                    std::sync::Mutex::new(std::collections::HashMap::new())
                });
                &MAP
            }

            /// Currently-open handle values, sorted — for the debug report.
            fn open_handles() -> Vec<i32> {
                let mut handles: Vec<i32> = Self::map()
                    .lock()
                    .unwrap_or_else(|poisoned| poisoned.into_inner())
                    .keys()
                    .copied()
                    .collect();
                handles.sort_unstable();
                handles
            }

            /// Store `value` and return its new handle. Never returns 0.
            pub(crate) fn insert(value: $ty) -> i32 {
                let value = std::sync::Arc::new(value);
                loop {
                    let handle = crate::handles::next_handle();
                    let mut map = Self::map()
                        .lock()
                        .unwrap_or_else(|poisoned| poisoned.into_inner());
                    // Occupied only after the shared counter wraps (2^31
                    // allocations) AND lands on a still-live handle — take
                    // the next number instead of silently replacing it.
                    if let std::collections::hash_map::Entry::Vacant(slot) = map.entry(handle) {
                        slot.insert(value);
                        return handle;
                    }
                }
            }

            /// Look up a handle. `None` if it was never issued or already freed.
            pub(crate) fn get(handle: i32) -> Option<std::sync::Arc<$ty>> {
                Self::map()
                    .lock()
                    .unwrap_or_else(|poisoned| poisoned.into_inner())
                    .get(&handle)
                    .cloned()
            }

            /// Drop the value behind `handle`. Returns whether it existed.
            pub(crate) fn remove(handle: i32) -> bool {
                Self::map()
                    .lock()
                    .unwrap_or_else(|poisoned| poisoned.into_inner())
                    .remove(&handle)
                    .is_some()
            }
        }
    };
}

/// Looks up `$handle` in `$registry`, or records an invalid-handle error and
/// returns `NominalErrorCode::InvalidHandle` from the enclosing function —
/// the prologue that starts almost every FFI function.
macro_rules! lookup_handle {
    ($registry:ty, $handle:expr) => {
        match <$registry>::get($handle) {
            Some(value) => value,
            None => {
                crate::error::set_last_error(format!(
                    "invalid {} handle: {}",
                    stringify!($registry),
                    $handle
                ));
                return crate::error::NominalErrorCode::InvalidHandle as i32;
            }
        }
    };
}

pub(crate) use {handle_registry, lookup_handle};

/// One counter shared by every registry, so a handle value can never be valid
/// in two registries at once — using an asset handle as a client handle fails
/// loudly instead of silently resolving to the wrong object. (After the
/// counter wraps — 2^31 allocations — that cross-registry guarantee weakens
/// to "practically always"; per-registry collision safety is preserved by
/// the vacant-slot check in `insert`.)
///
/// Wraps from `i32::MAX` back to 1, never issuing 0 (reserved as
/// "null"/"absent") or negatives.
pub(crate) fn next_handle() -> i32 {
    use std::sync::atomic::{AtomicI32, Ordering};
    static NEXT: AtomicI32 = AtomicI32::new(1);
    NEXT.fetch_update(Ordering::Relaxed, Ordering::Relaxed, |current| {
        Some(if current == i32::MAX { 1 } else { current + 1 })
    })
    .expect("fetch_update closure always returns Some")
}

// A list of handles is itself an opaque object behind a handle — this is how
// `_list`/`_search` return their results without any array or double pointer
// crossing the boundary (LabVIEW's wizard can't express either cleanly).
handle_registry!(HandleListHandle, Vec<i32>);

pub(crate) fn insert_handle_list(handles: Vec<i32>) -> i32 {
    HandleListHandle::insert(handles)
}

/// Stores the number of handles in the list in `out_count`.
#[no_mangle]
pub extern "C" fn nominal_handle_list_count(list: i32, out_count: *mut u32) -> i32 {
    guard(|| {
        let handles = lookup_handle!(HandleListHandle, list);
        if out_count.is_null() {
            return fail(NominalErrorCode::NullArgument, "out_count must not be null");
        }
        // SAFETY: out_count checked non-null above; caller owns it.
        unsafe { *out_count = handles.len() as u32 };
        0
    })
}

/// Stores the handle at `index` (0-based) in `out_handle`.
#[no_mangle]
pub extern "C" fn nominal_handle_list_get(list: i32, index: i32, out_handle: *mut i32) -> i32 {
    guard(|| {
        let handles = lookup_handle!(HandleListHandle, list);
        if out_handle.is_null() {
            return fail(
                NominalErrorCode::NullArgument,
                "out_handle must not be null",
            );
        }
        match usize::try_from(index).ok().and_then(|i| handles.get(i)) {
            Some(&handle) => {
                // SAFETY: out_handle checked non-null above; caller owns it.
                unsafe { *out_handle = handle };
                0
            }
            None => fail(
                NominalErrorCode::IndexOutOfRange,
                format!("index {index} out of range for list of {}", handles.len()),
            ),
        }
    })
}

/// Frees a handle list previously returned by a `_list`/`_search` function.
/// Frees only the list itself — the handles inside remain valid until passed
/// to their own `_free` function. Freeing twice returns an error.
#[no_mangle]
pub extern "C" fn nominal_handle_list_free(list: i32) -> i32 {
    guard(|| {
        if HandleListHandle::remove(list) {
            0
        } else {
            fail(
                NominalErrorCode::InvalidHandle,
                format!("invalid handle list: {list}"),
            )
        }
    })
}

// A staging list of RID strings, shared by every `_get_batch` function — the
// input-side counterpart of the handle list above. A C string array (char**)
// has no LabVIEW representation, so RIDs accumulate one call at a time.
handle_registry!(RidListHandle, Mutex<Vec<String>>);

/// Snapshot of the RIDs staged on `handle` — used by the `_get_batch`
/// functions after their own `lookup_handle!`.
pub(crate) fn rid_list_snapshot(list: &Mutex<Vec<String>>) -> Vec<String> {
    list.lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner())
        .clone()
}

/// Starts staging a list of RIDs for a `_get_batch` call. Add RIDs one at a
/// time with `nominal_rid_list_add`, pass the handle to any `_get_batch`
/// function (it is not consumed — one list can serve several calls), and
/// free it with `nominal_rid_list_free`.
#[no_mangle]
pub extern "C" fn nominal_rid_list_begin(out_list: *mut i32) -> i32 {
    guard(|| {
        if out_list.is_null() {
            return fail(NominalErrorCode::NullArgument, "out_list must not be null");
        }
        // SAFETY: out_list checked non-null above; caller owns it.
        unsafe { *out_list = RidListHandle::insert(Mutex::new(Vec::new())) };
        0
    })
}

/// Appends one RID to a staged RID list (repeatable; duplicates are kept).
#[no_mangle]
pub extern "C" fn nominal_rid_list_add(list: i32, rid: *const c_char) -> i32 {
    guard(|| {
        let list = lookup_handle!(RidListHandle, list);
        let rid = match read_required_str(rid, "rid") {
            Ok(value) => value,
            Err(code) => return code,
        };
        if rid.is_empty() {
            return fail(NominalErrorCode::InvalidArgument, "rid must not be empty");
        }
        list.lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner())
            .push(rid);
        0
    })
}

/// Frees a RID-list staging handle. Freeing twice returns an error.
#[no_mangle]
pub extern "C" fn nominal_rid_list_free(list: i32) -> i32 {
    guard(|| {
        if RidListHandle::remove(list) {
            0
        } else {
            fail(
                NominalErrorCode::InvalidHandle,
                format!("invalid rid list: {list}"),
            )
        }
    })
}

/// Debug aid: writes a report of every handle type that currently has open
/// (un-freed) handles into `buf`, one line per type —
/// `AssetHandle: 2 (17, 24)` — sorted by type name, with the open handle
/// values in parentheses. Writes an empty string when nothing is open, so
/// "needed == 0" at the end of a program means every handle was freed.
/// Same buffer convention as every other string getter. Handle values are
/// unique across all types (one shared counter), so a reported value
/// identifies the leaked handle unambiguously.
#[no_mangle]
pub extern "C" fn nominal_debug_open_handles(
    buf: *mut c_char,
    cap: u32,
    out_needed: *mut u32,
) -> i32 {
    guard(|| {
        // Snapshot the directory, then drop its lock BEFORE calling into the
        // per-registry enumerators — each of those takes its own map lock,
        // and a registry's first-touch initializer takes the directory lock.
        let directory: Vec<RegistryEntry> = REGISTRY_DIRECTORY
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner())
            .clone();

        let mut lines: Vec<String> = directory
            .into_iter()
            .filter_map(|(name, open_handles)| {
                let handles = open_handles();
                if handles.is_empty() {
                    return None;
                }
                let values = handles
                    .iter()
                    .map(i32::to_string)
                    .collect::<Vec<_>>()
                    .join(", ");
                Some(format!("{}: {} ({})", name, handles.len(), values))
            })
            .collect();
        // Directory order is first-touch order — sort for a stable report.
        lines.sort_unstable();
        write_str_field(&lines.join("\n"), buf, cap, out_needed)
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    handle_registry!(TestHandle, String);
    handle_registry!(OtherHandle, u32);

    #[test]
    fn insert_get_remove_round_trip() {
        let handle = TestHandle::insert("hello".to_string());
        assert!(handle > 0, "handle 0 is reserved");
        assert_eq!(*TestHandle::get(handle).unwrap(), "hello");
        assert!(TestHandle::remove(handle));
        assert!(TestHandle::get(handle).is_none());
        assert!(!TestHandle::remove(handle), "double free reports false");
    }

    #[test]
    fn zero_and_unknown_handles_are_invalid() {
        assert!(TestHandle::get(0).is_none());
        assert!(TestHandle::get(-1).is_none());
        assert!(TestHandle::get(i32::MAX).is_none());
    }

    #[test]
    fn handles_are_unique_across_registries() {
        let a = TestHandle::insert("a".to_string());
        let b = OtherHandle::insert(42);
        assert_ne!(a, b);
        assert!(TestHandle::get(b).is_none(), "cross-registry use must fail");
        assert!(OtherHandle::get(a).is_none());
        assert!(!OtherHandle::remove(a), "cross-registry free must fail");
        assert!(OtherHandle::remove(b));
    }

    /// Reads the full debug report via the standard two-call size-query
    /// dance (null buf for the size, then a right-sized buffer). Retries on
    /// BufferTooSmall: the report is process-global, so a parallel test can
    /// grow it between the size query and the fill.
    fn read_debug_report() -> String {
        loop {
            let mut needed = 0u32;
            assert_eq!(
                nominal_debug_open_handles(std::ptr::null_mut(), 0, &mut needed),
                0
            );
            let mut buf = vec![0u8; needed as usize + 1];
            let code =
                nominal_debug_open_handles(buf.as_mut_ptr().cast(), buf.len() as u32, &mut needed);
            if code == NominalErrorCode::BufferTooSmall as i32 {
                continue;
            }
            assert_eq!(code, 0);
            buf.truncate(needed as usize);
            return String::from_utf8(buf).expect("report is UTF-8");
        }
    }

    // Used by no other test — the report is process-global and unit tests
    // run in parallel, so assertions on shared registries would race.
    handle_registry!(DebugProbeHandle, u8);

    #[test]
    fn debug_report_tracks_open_and_freed_handles() {
        // The retry path sets a BufferTooSmall message — hold the lock like
        // every other test that can touch LAST_ERROR.
        let _guard = crate::error::test_message_lock();
        let first = DebugProbeHandle::insert(1);
        let second = DebugProbeHandle::insert(2);
        assert_eq!(*DebugProbeHandle::get(second).unwrap(), 2);

        // Both open: the probe line lists exactly these two, sorted.
        let report = read_debug_report();
        let expected = format!("DebugProbeHandle: 2 ({first}, {second})");
        assert!(
            report.lines().any(|line| line == expected),
            "expected line {expected:?} in report:\n{report}"
        );

        // One freed: the line shrinks to the survivor.
        assert!(DebugProbeHandle::remove(first));
        let report = read_debug_report();
        let expected = format!("DebugProbeHandle: 1 ({second})");
        assert!(
            report.lines().any(|line| line == expected),
            "expected line {expected:?} in report:\n{report}"
        );

        // All freed: the type disappears from the report entirely.
        assert!(DebugProbeHandle::remove(second));
        let report = read_debug_report();
        assert!(
            !report.contains("DebugProbeHandle"),
            "freed type must vanish from report:\n{report}"
        );
    }

    #[test]
    fn rid_list_round_trip() {
        let _guard = crate::error::test_message_lock();
        let mut list = 0i32;
        assert_eq!(nominal_rid_list_begin(&mut list), 0);

        let rid = std::ffi::CString::new("ri.scout.x.asset.1").unwrap();
        assert_eq!(nominal_rid_list_add(list, rid.as_ptr()), 0);
        let empty = std::ffi::CString::new("").unwrap();
        assert_eq!(
            nominal_rid_list_add(list, empty.as_ptr()),
            NominalErrorCode::InvalidArgument as i32
        );

        let staged = RidListHandle::get(list).unwrap();
        assert_eq!(rid_list_snapshot(&staged), vec!["ri.scout.x.asset.1"]);

        assert_eq!(nominal_rid_list_free(list), 0);
        assert_eq!(
            nominal_rid_list_free(list),
            NominalErrorCode::InvalidHandle as i32
        );
        assert_eq!(
            nominal_rid_list_add(list, rid.as_ptr()),
            NominalErrorCode::InvalidHandle as i32
        );
    }

    #[test]
    fn handle_list_round_trip() {
        let _guard = crate::error::test_message_lock();
        let list = insert_handle_list(vec![7, 8, 9]);

        let mut count = 0u32;
        assert_eq!(nominal_handle_list_count(list, &mut count), 0);
        assert_eq!(count, 3);

        let mut handle = 0i32;
        assert_eq!(nominal_handle_list_get(list, 2, &mut handle), 0);
        assert_eq!(handle, 9);

        assert_eq!(
            nominal_handle_list_get(list, 3, &mut handle),
            NominalErrorCode::IndexOutOfRange as i32
        );
        assert_eq!(
            nominal_handle_list_get(list, -1, &mut handle),
            NominalErrorCode::IndexOutOfRange as i32
        );

        assert_eq!(nominal_handle_list_free(list), 0);
        assert_eq!(
            nominal_handle_list_free(list),
            NominalErrorCode::InvalidHandle as i32
        );
        assert_eq!(
            nominal_handle_list_count(list, &mut count),
            NominalErrorCode::InvalidHandle as i32
        );
    }
}
