//! Handle registries: opaque objects cross the FFI boundary as `i64` handles.
//!
//! One registry per resource type, generated by [`handle_registry!`] — the
//! pattern is 100% mechanical, which is what makes it the right place for a
//! macro. Handle `0` is reserved and never issued, so it doubles as
//! "null"/"absent". Handles are process-global and thread-safe.

/// Generates a handle registry for one resource type:
/// a `Lazy<Mutex<HashMap<i64, Arc<T>>>>`, a shared `AtomicI64` counter, and
/// `insert`/`get`/`remove` functions scoped to that type.
///
/// ```ignore
/// handle_registry!(ClientHandle, nominal::core::NominalClient);
/// let h = ClientHandle::insert(client);      // -> new i64 handle (never 0)
/// let c = ClientHandle::get(h);              // -> Option<Arc<NominalClient>>
/// let existed = ClientHandle::remove(h);     // -> bool
/// ```
macro_rules! handle_registry {
    ($name:ident, $ty:ty) => {
        pub(crate) struct $name;

        impl $name {
            fn map(
            ) -> &'static std::sync::Mutex<std::collections::HashMap<i64, std::sync::Arc<$ty>>>
            {
                static MAP: once_cell::sync::Lazy<
                    std::sync::Mutex<std::collections::HashMap<i64, std::sync::Arc<$ty>>>,
                > = once_cell::sync::Lazy::new(|| {
                    std::sync::Mutex::new(std::collections::HashMap::new())
                });
                &MAP
            }

            /// Store `value` and return its new handle. Never returns 0.
            pub(crate) fn insert(value: $ty) -> i64 {
                let handle = crate::handles::next_handle();
                Self::map()
                    .lock()
                    .unwrap_or_else(|poisoned| poisoned.into_inner())
                    .insert(handle, std::sync::Arc::new(value));
                handle
            }

            /// Look up a handle. `None` if it was never issued or already freed.
            pub(crate) fn get(handle: i64) -> Option<std::sync::Arc<$ty>> {
                Self::map()
                    .lock()
                    .unwrap_or_else(|poisoned| poisoned.into_inner())
                    .get(&handle)
                    .cloned()
            }

            /// Drop the value behind `handle`. Returns whether it existed.
            pub(crate) fn remove(handle: i64) -> bool {
                Self::map()
                    .lock()
                    .unwrap_or_else(|poisoned| poisoned.into_inner())
                    .remove(&handle)
                    .is_some()
            }
        }
    };
}

/// Looks up `$handle` in `$registry`, or records an invalid-handle error and
/// returns `$err_ret` from the enclosing function — the prologue that starts
/// almost every FFI function. `$err_ret` is spelled out because action
/// functions return `i32` codes while getters return negated `i64` codes.
macro_rules! lookup_handle {
    ($registry:ty, $handle:expr, $err_ret:expr) => {
        match <$registry>::get($handle) {
            Some(value) => value,
            None => {
                crate::error::set_last_error(format!(
                    "invalid {} handle: {}",
                    stringify!($registry),
                    $handle
                ));
                return $err_ret;
            }
        }
    };
}

pub(crate) use {handle_registry, lookup_handle};

/// One counter shared by every registry, so a handle value can never be valid
/// in two registries at once — using an asset handle as a client handle fails
/// loudly instead of silently resolving to the wrong object.
pub(crate) fn next_handle() -> i64 {
    static NEXT: std::sync::atomic::AtomicI64 = std::sync::atomic::AtomicI64::new(1);
    NEXT.fetch_add(1, std::sync::atomic::Ordering::Relaxed)
}

/// Hand a `Vec` of handles to the caller as a raw array. Paired with
/// [`nominal_handle_array_free`].
pub(crate) fn handles_into_raw(handles: Vec<i64>) -> (*mut i64, usize) {
    let boxed = handles.into_boxed_slice();
    let count = boxed.len();
    (Box::into_raw(boxed) as *mut i64, count)
}

/// Frees a handle array previously returned by a `_list`/`_search` function.
/// Frees only the array itself — the handles inside remain valid until passed
/// to their own `_free` function. `count` must be exactly the count the array
/// was returned with. A null `ptr` with `count` 0 is a no-op.
#[no_mangle]
pub extern "C" fn nominal_handle_array_free(ptr: *mut i64, count: usize) -> i32 {
    crate::error::guard(|| {
        if ptr.is_null() {
            if count == 0 {
                return 0;
            }
            return crate::error::fail(
                crate::error::NominalErrorCode::NullArgument,
                "handle array pointer is null but count is non-zero",
            );
        }
        // SAFETY: ptr/count came from handles_into_raw, which leaked a boxed
        // slice — length and capacity are both `count`.
        unsafe { drop(Vec::from_raw_parts(ptr, count, count)) };
        0
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    handle_registry!(TestHandle, String);
    handle_registry!(OtherHandle, u32);

    #[test]
    fn insert_get_remove_round_trip() {
        let handle = TestHandle::insert("hello".to_string());
        assert!(handle > 0, "handle 0 is reserved");
        assert_eq!(*TestHandle::get(handle).unwrap(), "hello");
        assert!(TestHandle::remove(handle));
        assert!(TestHandle::get(handle).is_none());
        assert!(!TestHandle::remove(handle), "double free reports false");
    }

    #[test]
    fn zero_and_unknown_handles_are_invalid() {
        assert!(TestHandle::get(0).is_none());
        assert!(TestHandle::get(-1).is_none());
        assert!(TestHandle::get(i64::MAX).is_none());
    }

    #[test]
    fn handles_are_unique_across_registries() {
        let a = TestHandle::insert("a".to_string());
        let b = OtherHandle::insert(42);
        assert_ne!(a, b);
        assert!(TestHandle::get(b).is_none(), "cross-registry use must fail");
        assert!(OtherHandle::get(a).is_none());
        assert!(!OtherHandle::remove(a), "cross-registry free must fail");
        assert!(OtherHandle::remove(b));
    }

    #[test]
    fn handle_array_free_round_trip() {
        let (ptr, count) = handles_into_raw(vec![1, 2, 3]);
        assert_eq!(count, 3);
        assert_eq!(nominal_handle_array_free(ptr, count), 0);
    }

    #[test]
    fn handle_array_free_null_rules() {
        assert_eq!(nominal_handle_array_free(std::ptr::null_mut(), 0), 0);
        assert_ne!(nominal_handle_array_free(std::ptr::null_mut(), 3), 0);
    }
}
