/*
 * nominal_ffi.h — C ABI for the Nominal Rust SDK, generated by cbindgen.
 * DO NOT EDIT — regenerate with `cargo build -p ffi`.
 *
 * Conventions (see error.rs for full details):
 *   - Every function returns int32_t: 0 = success, non-zero = a
 *     NominalErrorCode value. All results come back through out-parameters.
 *     Fetch the message for the most recent error with nominal_last_error().
 *   - Strings out: caller supplies a byte buffer + uint32_t capacity; the
 *     byte count needed (excluding the null terminator) is stored in a
 *     uint32_t out-parameter. A null buffer is the supported size query.
 *     A non-null buffer that is too small returns BufferTooSmall and writes
 *     nothing — retry with (needed + 1) bytes.
 *   - Opaque objects are int32_t handles. Handle 0 is never valid and
 *     doubles as "null"/"absent". _list/_search results are handle lists:
 *     read with nominal_handle_list_get, free with nominal_handle_list_free.
 *   - Timestamps are double Unix milliseconds (UTC).
 *   - No 64-bit integers appear anywhere in this API: LabVIEW's Import
 *     Shared Library wizard cannot parse them.
 */

#ifndef NOMINAL_FFI_H
#define NOMINAL_FFI_H


/* Self-contained type definitions: LabVIEW's wizard ships no standard
 * headers. Real compilers (MSVC/GCC/Clang) take the #include branch.
 * Only 8/16/32-bit types appear here — LabVIEW's wizard cannot parse any
 * 64-bit integer type, which is why this API defines none. */
#ifdef _MSC_VER
#include <stdint.h>
#include <stdbool.h>
#else
#ifdef __GNUC__
#include <stdint.h>
#include <stdbool.h>
#else
typedef signed char    int8_t;
typedef unsigned char  uint8_t;
typedef short          int16_t;
typedef unsigned short uint16_t;
typedef int            int32_t;
typedef unsigned int   uint32_t;
typedef unsigned char  bool;
#endif
#endif


/*
 Error codes returned by every function in this library.
 */
enum NominalErrorCode
#if __STDC_VERSION__ >= 202311L
  : int32_t
#endif // __STDC_VERSION__ >= 202311L
 {
  /*
   Success.
   */
  NominalErrorCode_Ok = 0,
  /*
   A Rust panic was caught at the FFI boundary. State may be suspect;
   report this as a bug in the FFI layer.
   */
  NominalErrorCode_Panic = 1,
  /*
   A required pointer argument was null.
   */
  NominalErrorCode_NullArgument = 2,
  /*
   A string argument was not valid UTF-8.
   */
  NominalErrorCode_InvalidUtf8 = 3,
  /*
   A handle was never issued or has already been freed.
   */
  NominalErrorCode_InvalidHandle = 4,
  /*
   An argument was rejected before any request was sent (bad RID, bad
   token, bad URL, conflicting filters, ...).
   */
  NominalErrorCode_InvalidArgument = 5,
  /*
   An index argument was out of range for the collection.
   */
  NominalErrorCode_IndexOutOfRange = 6,
  /*
   The requested resource does not exist.
   */
  NominalErrorCode_NotFound = 7,
  /*
   The Nominal API returned an error or an unreadable response.
   */
  NominalErrorCode_ApiError = 8,
  /*
   Any other error from the underlying `nominal` SDK.
   */
  NominalErrorCode_SdkError = 9,
  /*
   A caller-supplied output buffer was too small; nothing was written.
   The needed-bytes out-parameter says how much to allocate (+ 1 for the
   null terminator).
   */
  NominalErrorCode_BufferTooSmall = 10,
};
#if __STDC_VERSION__ >= 202311L
typedef enum NominalErrorCode NominalErrorCode;
#else
typedef int32_t NominalErrorCode;
#endif // __STDC_VERSION__ >= 202311L

/*
 The kind of a data source attached to an asset, as returned by
 `nominal_asset_data_source_type_at`.
 */
enum NominalDataSourceType
#if __STDC_VERSION__ >= 202311L
  : int32_t
#endif // __STDC_VERSION__ >= 202311L
 {
  NominalDataSourceType_Dataset = 0,
  NominalDataSourceType_Video = 1,
  NominalDataSourceType_Connection = 2,
};
#if __STDC_VERSION__ >= 202311L
typedef enum NominalDataSourceType NominalDataSourceType;
#else
typedef int32_t NominalDataSourceType;
#endif // __STDC_VERSION__ >= 202311L

/*
 Creates an asset with the given name and (optional, may be null or empty)
 description, writing the new asset's handle to `out_asset`.
 Free with `nominal_asset_free`.
 */
int32_t nominal_asset_create(int32_t client,
                             const char *name,
                             const char *description,
                             int32_t *out_asset);

/*
 Fetches the asset with the given RID, writing its handle to `out_asset`.
 Free with `nominal_asset_free`.
 */
int32_t nominal_asset_get(int32_t client, const char *rid, int32_t *out_asset);

/*
 Lists all assets (newest first), returning a handle list.

 On success `*out_list` is a handle list of `*out_count` asset handles —
 read them with `nominal_handle_list_get` and free the list with
 `nominal_handle_list_free`. Each asset handle stays valid until passed to
 `nominal_asset_free`, independent of the list.
 */
int32_t nominal_asset_list(int32_t client, int32_t *out_list, uint32_t *out_count);

/*
 Searches assets, returning a handle list (see `nominal_asset_list` for
 ownership).

 Filters may each be null or empty ("no filter"); the ones provided are
 combined with AND:
 - `search_text`: fuzzy full-text match on name and description
 - `label`: exact label match
 - `property_key` + `property_value`: property match (both or neither)
 */
int32_t nominal_asset_search(int32_t client,
                             const char *search_text,
                             const char *label,
                             const char *property_key,
                             const char *property_value,
                             int32_t *out_list,
                             uint32_t *out_count);

/*
 Updates an asset's name and/or description. Null or empty arguments leave
 that field unchanged. Writes a handle to the updated asset to `out_asset`
 (free with `nominal_asset_free`); handles to the old version stay valid
 but keep their stale field values.
 */
int32_t nominal_asset_update(int32_t client,
                             const char *rid,
                             const char *name,
                             const char *description,
                             int32_t *out_asset);

/*
 Starts staging an asset-create request with the (required) name. Add
 optional fields with the `nominal_asset_create_set_*` / `_add_*` calls,
 then fire it with `nominal_asset_create_commit`. Free with
 `nominal_asset_create_free` (commit does not free).
 */
int32_t nominal_asset_create_begin(const char *name, int32_t *out_staging);

/*
 Sets the description on a staged create (overwrites any previous value;
 empty clears it).
 */
int32_t nominal_asset_create_set_description(int32_t staging, const char *description);

/*
 Adds one label to a staged create (duplicates are collapsed server-side).
 */
int32_t nominal_asset_create_add_label(int32_t staging, const char *label);

/*
 Sets one property on a staged create (same key overwrites).
 */
int32_t nominal_asset_create_set_property(int32_t staging, const char *key, const char *value);

/*
 Creates the staged asset, writing the new asset's handle to `out_asset`
 (free with `nominal_asset_free`). The staging handle stays valid — free it
 with `nominal_asset_create_free`, or commit it again for another asset.
 */
int32_t nominal_asset_create_commit(int32_t client, int32_t staging, int32_t *out_asset);

/*
 Frees an asset-create staging handle. Freeing twice returns an error.
 */
int32_t nominal_asset_create_free(int32_t staging);

/*
 Starts staging an asset update. Only fields set via the
 `nominal_asset_update_set_*` / `_add_*` calls are changed at commit; the
 rest remain untouched. Free with `nominal_asset_update_free`.
 */
int32_t nominal_asset_update_begin(int32_t *out_staging);

/*
 Stages a new name.
 */
int32_t nominal_asset_update_set_name(int32_t staging, const char *name);

/*
 Stages a new description (empty clears the description).
 */
int32_t nominal_asset_update_set_description(int32_t staging, const char *description);

/*
 Adds one label to the staged update. NOTE: touching labels at all means
 the commit REPLACES the asset's entire label set with exactly the labels
 accumulated here (upstream semantics) — to keep existing labels, add them
 too.
 */
int32_t nominal_asset_update_add_label(int32_t staging, const char *label);

/*
 Sets one property on the staged update (same key overwrites). NOTE: same
 replace semantics as labels — touching properties at all means the commit
 replaces the asset's entire property map with the ones accumulated here.
 */
int32_t nominal_asset_update_set_property(int32_t staging, const char *key, const char *value);

/*
 Applies the staged update to the asset with the given RID, writing a
 handle to the updated asset to `out_asset` (free with
 `nominal_asset_free`). At least one field must have been staged. The
 staging handle stays valid — free it with `nominal_asset_update_free`.
 */
int32_t nominal_asset_update_commit(int32_t client,
                                    const char *rid,
                                    int32_t staging,
                                    int32_t *out_asset);

/*
 Frees an asset-update staging handle. Freeing twice returns an error.
 */
int32_t nominal_asset_update_free(int32_t staging);

/*
 Attaches the dataset with `dataset_rid` to the asset with `rid` under
 `scope_name`, writing a handle to the updated asset to `out_asset` (free
 with `nominal_asset_free`).
 */
int32_t nominal_asset_add_dataset(int32_t client,
                                  const char *rid,
                                  const char *scope_name,
                                  const char *dataset_rid,
                                  int32_t *out_asset);

/*
 Attaches the video with `video_rid` to the asset with `rid` under
 `scope_name`, writing a handle to the updated asset to `out_asset` (free
 with `nominal_asset_free`).
 */
int32_t nominal_asset_add_video(int32_t client,
                                const char *rid,
                                const char *scope_name,
                                const char *video_rid,
                                int32_t *out_asset);

/*
 Attaches the connection with `connection_rid` to the asset with `rid`
 under `scope_name`, writing a handle to the updated asset to `out_asset`
 (free with `nominal_asset_free`).
 */
int32_t nominal_asset_add_connection(int32_t client,
                                     const char *rid,
                                     const char *scope_name,
                                     const char *connection_rid,
                                     int32_t *out_asset);

/*
 Starts staging a dataset attach with series-tag filters (tags select which
 series from the dataset are included in the asset's data scope). Add tags
 with `nominal_asset_attach_dataset_add_tag`, then fire it with
 `nominal_asset_attach_dataset_commit`. Free with
 `nominal_asset_attach_dataset_free` (commit does not free). For an attach
 without tags, the flat `nominal_asset_add_dataset` is simpler.
 */
int32_t nominal_asset_attach_dataset_begin(const char *scope_name,
                                           const char *dataset_rid,
                                           int32_t *out_staging);

/*
 Adds one series-tag filter to a staged dataset attach (same key
 overwrites).
 */
int32_t nominal_asset_attach_dataset_add_tag(int32_t staging, const char *key, const char *value);

/*
 Attaches the staged dataset (with its accumulated series tags) to the
 asset with `rid`, writing a handle to the updated asset to `out_asset`
 (free with `nominal_asset_free`). The staging handle stays valid — free it
 with `nominal_asset_attach_dataset_free`, or commit it again against
 another asset.
 */
int32_t nominal_asset_attach_dataset_commit(int32_t client,
                                            const char *rid,
                                            int32_t staging,
                                            int32_t *out_asset);

/*
 Frees a dataset-attach staging handle. Freeing twice returns an error.
 */
int32_t nominal_asset_attach_dataset_free(int32_t staging);

/*
 Archives an asset (hidden from the UI, not deleted).
 */
int32_t nominal_asset_archive(int32_t client, const char *rid);

/*
 Unarchives an asset, restoring its visibility in the UI.
 */
int32_t nominal_asset_unarchive(int32_t client, const char *rid);

/*
 Frees an asset handle. Freeing twice returns an error.
 */
int32_t nominal_asset_free(int32_t asset);

/*
 Writes the asset's RID into `buf`, storing the byte count needed in
 `out_needed`.
 */
int32_t nominal_asset_rid(int32_t asset, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Writes the asset's name into `buf`, storing the byte count needed in
 `out_needed`.
 */
int32_t nominal_asset_name(int32_t asset, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Writes the asset's description into `buf`, and whether one is set into
 `is_present` (an absent description reports 0 bytes needed).
 */
int32_t nominal_asset_description(int32_t asset,
                                  char *buf,
                                  uint32_t cap,
                                  uint32_t *out_needed,
                                  bool *is_present);

/*
 Writes the URL for viewing this asset in the Nominal web app into `buf`,
 storing the byte count needed in `out_needed`.
 */
int32_t nominal_asset_url(int32_t asset, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Writes the asset's creation time to `out_millis` as Unix milliseconds
 (UTC), as a `double` — exact for whole milliseconds up to 2^53 (LabVIEW's
 import wizard cannot parse 64-bit integer types, so `i64` is not an
 option here).
 */
int32_t nominal_asset_created_at(int32_t asset, double *out_millis);

/*
 Stores the number of properties on the asset in `out_count`.
 */
int32_t nominal_asset_property_count(int32_t asset, uint32_t *out_count);

/*
 Writes the key of the property at `index` (0-based, sorted-key order) into
 `buf`, storing the byte count needed in `out_needed`.
 */
int32_t nominal_asset_property_key_at(int32_t asset,
                                      int32_t index,
                                      char *buf,
                                      uint32_t cap,
                                      uint32_t *out_needed);

/*
 Writes the value of the property at `index` (0-based, sorted-key order)
 into `buf`, storing the byte count needed in `out_needed`.
 */
int32_t nominal_asset_property_value_at(int32_t asset,
                                        int32_t index,
                                        char *buf,
                                        uint32_t cap,
                                        uint32_t *out_needed);

/*
 Stores the number of labels on the asset in `out_count`.
 */
int32_t nominal_asset_label_count(int32_t asset, uint32_t *out_count);

/*
 Writes the label at `index` (0-based) into `buf`, storing the byte count
 needed in `out_needed`.
 */
int32_t nominal_asset_label_at(int32_t asset,
                               int32_t index,
                               char *buf,
                               uint32_t cap,
                               uint32_t *out_needed);

/*
 Stores the number of data sources attached to the asset in `out_count`.
 */
int32_t nominal_asset_data_source_count(int32_t asset, uint32_t *out_count);

/*
 Writes the scope name of the data source at `index` (0-based, sorted-name
 order) into `buf`, storing the byte count needed in `out_needed`.
 */
int32_t nominal_asset_data_source_name_at(int32_t asset,
                                          int32_t index,
                                          char *buf,
                                          uint32_t cap,
                                          uint32_t *out_needed);

/*
 Writes the RID of the data source at `index` (0-based, sorted-name order)
 into `buf`, storing the byte count needed in `out_needed`.
 */
int32_t nominal_asset_data_source_rid_at(int32_t asset,
                                         int32_t index,
                                         char *buf,
                                         uint32_t cap,
                                         uint32_t *out_needed);

/*
 Writes the kind of the data source at `index` (0-based, sorted-name order)
 to `out_type` as a `NominalDataSourceType` value.
 */
int32_t nominal_asset_data_source_type_at(int32_t asset, int32_t index, int32_t *out_type);

/*
 Lists every channel on a data source (dataset, video, or connection RID),
 returning a handle list.

 On success `*out_list` is a handle list of `*out_count` channel handles —
 read them with `nominal_handle_list_get` and free the list with
 `nominal_handle_list_free`. Each channel handle stays valid until passed
 to `nominal_channel_free`, independent of the list.
 */
int32_t nominal_channel_list(int32_t client,
                             const char *data_source_rid,
                             int32_t *out_list,
                             uint32_t *out_count);

/*
 Searches channels, returning a handle list (see `nominal_channel_list`
 for ownership).

 Filters are optional and combined with AND:
 - `data_source_rid`: restrict to one data source (null or empty = all the
   caller can see — expect that to be slow on large workspaces)
 - `substring`: case-insensitive substring the channel name must contain
 - `data_type`: a `NominalChannelDataType` value, or -1 for no filter
 */
int32_t nominal_channel_search(int32_t client,
                               const char *data_source_rid,
                               const char *substring,
                               int32_t data_type,
                               int32_t *out_list,
                               uint32_t *out_count);

/*
 Fetches one channel's metadata by data-source RID and channel name,
 writing its handle to `out_channel`. Free with `nominal_channel_free`.
 */
int32_t nominal_channel_get(int32_t client,
                            const char *data_source_rid,
                            const char *name,
                            int32_t *out_channel);

/*
 Sets a channel's editable metadata. `data_type` (a `NominalChannelDataType`
 value) is required — the upsert endpoint needs it when the metadata record
 doesn't exist yet. `description` and `unit` are optional (null or empty =
 leave untouched); pass `clear_unit` true to remove an existing unit
 (mutually exclusive with `unit`). Writes a handle reflecting the updated
 metadata to `out_channel` (free with `nominal_channel_free`).
 */
int32_t nominal_channel_set_metadata(int32_t client,
                                     const char *data_source_rid,
                                     const char *name,
                                     int32_t data_type,
                                     const char *description,
                                     const char *unit,
                                     bool clear_unit,
                                     int32_t *out_channel);

/*
 Frees a channel handle. Freeing twice returns an error.
 */
int32_t nominal_channel_free(int32_t channel);

/*
 Writes the channel's name into `buf`, storing the byte count needed in
 `out_needed`.
 */
int32_t nominal_channel_name(int32_t channel, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Writes the RID of the data source that owns this channel into `buf`,
 storing the byte count needed in `out_needed`.
 */
int32_t nominal_channel_data_source_rid(int32_t channel,
                                        char *buf,
                                        uint32_t cap,
                                        uint32_t *out_needed);

/*
 Writes the channel's description into `buf`, and whether one is set into
 `is_present` (an absent description reports 0 bytes needed).
 */
int32_t nominal_channel_description(int32_t channel,
                                    char *buf,
                                    uint32_t cap,
                                    uint32_t *out_needed,
                                    bool *is_present);

/*
 Writes the channel's unit symbol (e.g. "m/s") into `buf`, and whether one
 is set into `is_present` (an absent unit reports 0 bytes needed).
 */
int32_t nominal_channel_unit(int32_t channel,
                             char *buf,
                             uint32_t cap,
                             uint32_t *out_needed,
                             bool *is_present);

/*
 Stores the channel's data type in `out_type` as a
 `NominalChannelDataType` value (`Unknown` = 10 for types this library
 doesn't recognize).
 */
int32_t nominal_channel_data_type(int32_t channel, int32_t *out_type);

/*
 Creates a Nominal API client and writes its handle to `out_client`.

 `token` is required. `workspace_rid` and `base_url` may be null or empty:
 an absent workspace uses the token's default workspace, and an absent base
 URL uses the production API. No network traffic happens here — a bad token
 fails on the first request, not at construction.

 Free with `nominal_client_free`.
 */
int32_t nominal_client_new(const char *token,
                           const char *workspace_rid,
                           const char *base_url,
                           int32_t *out_client);

/*
 Frees a client handle. The handle is invalid afterwards; freeing twice
 returns an error. Asset (and other resource) handles obtained through this
 client stay valid — they hold their own data.
 */
int32_t nominal_client_free(int32_t client);

/*
 Writes the client's API base URL into `buf` (capacity `cap` bytes),
 storing the byte count needed in `out_needed` — see the string convention
 in the header preamble.
 */
int32_t nominal_client_base_url(int32_t client, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Writes the client's workspace RID into `buf` and whether one is configured
 into `is_present` (an absent workspace reports 0 bytes needed).
 */
int32_t nominal_client_workspace_rid(int32_t client,
                                     char *buf,
                                     uint32_t cap,
                                     uint32_t *out_needed,
                                     bool *is_present);

/*
 Creates an empty dataset with the given name and (optional, may be null
 or empty) description, writing the new dataset's handle to `out_dataset`.
 Data is added by ingest, separately. Free with `nominal_dataset_free`.
 For labels, properties, or a channel delimiter use the
 `nominal_dataset_create_begin` staging flow instead.
 */
int32_t nominal_dataset_create(int32_t client,
                               const char *name,
                               const char *description,
                               int32_t *out_dataset);

/*
 Fetches the dataset with the given RID, writing its handle to
 `out_dataset`. Free with `nominal_dataset_free`.
 */
int32_t nominal_dataset_get(int32_t client, const char *rid, int32_t *out_dataset);

/*
 Lists all datasets (newest first), returning a handle list.

 On success `*out_list` is a handle list of `*out_count` dataset handles —
 read them with `nominal_handle_list_get` and free the list with
 `nominal_handle_list_free`. Each dataset handle stays valid until passed
 to `nominal_dataset_free`, independent of the list.
 */
int32_t nominal_dataset_list(int32_t client, int32_t *out_list, uint32_t *out_count);

/*
 Searches datasets, returning a handle list (see `nominal_dataset_list`
 for ownership).

 Filters may each be null or empty ("no filter"); the ones provided are
 combined with AND:
 - `search_text`: fuzzy full-text match on name and description
 - `label`: exact label match
 - `property_key` + `property_value`: property match (both or neither)
 */
int32_t nominal_dataset_search(int32_t client,
                               const char *search_text,
                               const char *label,
                               const char *property_key,
                               const char *property_value,
                               int32_t *out_list,
                               uint32_t *out_count);

/*
 Updates a dataset's name and/or description. Null or empty arguments
 leave that field unchanged. Writes a handle to the updated dataset to
 `out_dataset` (free with `nominal_dataset_free`). For labels or
 properties use the `nominal_dataset_update_begin` staging flow instead.
 */
int32_t nominal_dataset_update(int32_t client,
                               const char *rid,
                               const char *name,
                               const char *description,
                               int32_t *out_dataset);

/*
 Archives a dataset (hidden from the UI, not deleted).
 */
int32_t nominal_dataset_archive(int32_t client, const char *rid);

/*
 Unarchives a dataset, restoring its visibility in the UI.
 */
int32_t nominal_dataset_unarchive(int32_t client, const char *rid);

/*
 Frees a dataset handle. Freeing twice returns an error.
 */
int32_t nominal_dataset_free(int32_t dataset);

/*
 Starts staging a dataset-create request with the (required) name. Add
 optional fields with the `nominal_dataset_create_set_*` / `_add_*` calls,
 then fire it with `nominal_dataset_create_commit`. Free with
 `nominal_dataset_create_free` (commit does not free).
 */
int32_t nominal_dataset_create_begin(const char *name, int32_t *out_staging);

/*
 Sets the description on a staged dataset create (empty clears it).
 */
int32_t nominal_dataset_create_set_description(int32_t staging, const char *description);

/*
 Sets the channel-name delimiter on a staged dataset create (e.g. "." to
 group channels like "engine.temp" into a prefix tree in the UI).
 */
int32_t nominal_dataset_create_set_channel_delimiter(int32_t staging, const char *delimiter);

/*
 Adds one label to a staged dataset create.
 */
int32_t nominal_dataset_create_add_label(int32_t staging, const char *label);

/*
 Sets one property on a staged dataset create (same key overwrites).
 */
int32_t nominal_dataset_create_set_property(int32_t staging, const char *key, const char *value);

/*
 Creates the staged dataset, writing the new dataset's handle to
 `out_dataset` (free with `nominal_dataset_free`). The staging handle
 stays valid — free it with `nominal_dataset_create_free`.
 */
int32_t nominal_dataset_create_commit(int32_t client, int32_t staging, int32_t *out_dataset);

/*
 Frees a dataset-create staging handle. Freeing twice returns an error.
 */
int32_t nominal_dataset_create_free(int32_t staging);

/*
 Starts staging a dataset update. Only fields set via the
 `nominal_dataset_update_set_*` / `_add_*` calls are changed at commit;
 the rest remain untouched. Free with `nominal_dataset_update_free`.
 */
int32_t nominal_dataset_update_begin(int32_t *out_staging);

/*
 Stages a new name.
 */
int32_t nominal_dataset_update_set_name(int32_t staging, const char *name);

/*
 Stages a new description (empty clears the description).
 */
int32_t nominal_dataset_update_set_description(int32_t staging, const char *description);

/*
 Adds one label to the staged update. NOTE: touching labels at all means
 the commit REPLACES the dataset's entire label set with exactly the
 labels accumulated here (upstream semantics) — to keep existing labels,
 add them too.
 */
int32_t nominal_dataset_update_add_label(int32_t staging, const char *label);

/*
 Sets one property on the staged update (same key overwrites). NOTE: same
 replace semantics as labels — touching properties at all means the commit
 replaces the dataset's entire property map with the ones accumulated
 here.
 */
int32_t nominal_dataset_update_set_property(int32_t staging, const char *key, const char *value);

/*
 Applies the staged update to the dataset with the given RID, writing a
 handle to the updated dataset to `out_dataset` (free with
 `nominal_dataset_free`). At least one field must have been staged. The
 staging handle stays valid — free it with `nominal_dataset_update_free`.
 */
int32_t nominal_dataset_update_commit(int32_t client,
                                      const char *rid,
                                      int32_t staging,
                                      int32_t *out_dataset);

/*
 Frees a dataset-update staging handle. Freeing twice returns an error.
 */
int32_t nominal_dataset_update_free(int32_t staging);

/*
 Writes the dataset's RID into `buf`, storing the byte count needed in
 `out_needed`.
 */
int32_t nominal_dataset_rid(int32_t dataset, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Writes the dataset's name into `buf`, storing the byte count needed in
 `out_needed`.
 */
int32_t nominal_dataset_name(int32_t dataset, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Writes the dataset's description into `buf`, and whether one is set into
 `is_present` (an absent description reports 0 bytes needed).
 */
int32_t nominal_dataset_description(int32_t dataset,
                                    char *buf,
                                    uint32_t cap,
                                    uint32_t *out_needed,
                                    bool *is_present);

/*
 Writes the URL for viewing this dataset in the Nominal web app into
 `buf`, storing the byte count needed in `out_needed`.
 */
int32_t nominal_dataset_url(int32_t dataset, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Writes the dataset's creation (first-ingest) time to `out_millis` as
 `f64` Unix milliseconds (UTC).
 */
int32_t nominal_dataset_created_at(int32_t dataset, double *out_millis);

/*
 Stores the number of properties on the dataset in `out_count`.
 */
int32_t nominal_dataset_property_count(int32_t dataset, uint32_t *out_count);

/*
 Writes the key of the property at `index` (0-based, sorted-key order)
 into `buf`, storing the byte count needed in `out_needed`.
 */
int32_t nominal_dataset_property_key_at(int32_t dataset,
                                        int32_t index,
                                        char *buf,
                                        uint32_t cap,
                                        uint32_t *out_needed);

/*
 Writes the value of the property at `index` (0-based, sorted-key order)
 into `buf`, storing the byte count needed in `out_needed`.
 */
int32_t nominal_dataset_property_value_at(int32_t dataset,
                                          int32_t index,
                                          char *buf,
                                          uint32_t cap,
                                          uint32_t *out_needed);

/*
 Stores the number of labels on the dataset in `out_count`.
 */
int32_t nominal_dataset_label_count(int32_t dataset, uint32_t *out_count);

/*
 Writes the label at `index` (0-based) into `buf`, storing the byte count
 needed in `out_needed`.
 */
int32_t nominal_dataset_label_at(int32_t dataset,
                                 int32_t index,
                                 char *buf,
                                 uint32_t cap,
                                 uint32_t *out_needed);

/*
 Writes the most recent error message into `buf` (capacity `cap`, in
 bytes) and stores the byte count needed (excluding the null terminator)
 in `out_needed`. Call after any function returns a non-zero code.

 A null `buf` is the supported size query. If `buf` is non-null but too
 small, returns `BufferTooSmall` WITHOUT overwriting the stored message —
 retry with a buffer of at least (`*out_needed` + 1) bytes.
 */
int32_t nominal_last_error(char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Stores the number of handles in the list in `out_count`.
 */
int32_t nominal_handle_list_count(int32_t list, uint32_t *out_count);

/*
 Stores the handle at `index` (0-based) in `out_handle`.
 */
int32_t nominal_handle_list_get(int32_t list, int32_t index, int32_t *out_handle);

/*
 Frees a handle list previously returned by a `_list`/`_search` function.
 Frees only the list itself — the handles inside remain valid until passed
 to their own `_free` function. Freeing twice returns an error.
 */
int32_t nominal_handle_list_free(int32_t list);

/*
 Starts staging options for a CSV or Parquet ingest. Set the (required)
 timestamp spec with one of the `nominal_ingest_tabular_set_timestamp_*`
 calls, add optional settings, then fire it with `nominal_ingest_csv` or
 `nominal_ingest_parquet`. Free with `nominal_ingest_tabular_free` (the
 ingest calls do not free, so one staging handle can serve several files).
 */
int32_t nominal_ingest_tabular_begin(int32_t *out_staging);

/*
 Timestamps are ISO 8601 strings in the named column.
 */
int32_t nominal_ingest_tabular_set_timestamp_iso8601(int32_t staging, const char *column);

/*
 Timestamps are numeric epochs in the named column, in the given
 `NominalTimeUnit` (e.g. epoch-seconds).
 */
int32_t nominal_ingest_tabular_set_timestamp_epoch(int32_t staging,
                                                   const char *column,
                                                   int32_t time_unit);

/*
 Timestamps use a custom format string (Java `DateTimeFormatter` syntax)
 in the named column. `default_year` / `default_day_of_year` fill in
 missing date parts for formats like IRIG; pass 0 to leave unset.
 */
int32_t nominal_ingest_tabular_set_timestamp_custom(int32_t staging,
                                                    const char *column,
                                                    const char *format,
                                                    int32_t default_year,
                                                    int32_t default_day_of_year);

/*
 Timestamps are numeric offsets in the named column, in the given
 `NominalTimeUnit`, relative to a start time. `offset_ms` (`f64` Unix
 milliseconds, with `has_offset` true) anchors the offsets — required when
 ingesting into an existing dataset.
 */
int32_t nominal_ingest_tabular_set_timestamp_relative(int32_t staging,
                                                      const char *column,
                                                      int32_t time_unit,
                                                      double offset_ms,
                                                      bool has_offset);

/*
 Prefixes every channel name in the file with the given string.
 */
int32_t nominal_ingest_tabular_set_channel_prefix(int32_t staging, const char *prefix);

/*
 Derives the given tag's value from the named column (repeatable).
 */
int32_t nominal_ingest_tabular_add_tag_column(int32_t staging, const char *tag, const char *column);

/*
 Applies a fixed tag value to every row in the file (repeatable).
 */
int32_t nominal_ingest_tabular_add_file_tag(int32_t staging, const char *tag, const char *value);

/*
 Excludes the named column from ingestion (repeatable).
 */
int32_t nominal_ingest_tabular_exclude_column(int32_t staging, const char *column);

/*
 Marks the file as an archive (.tar, .tar.gz, .zip) whose .parquet entries
 will be extracted and ingested. Parquet only — `nominal_ingest_csv`
 rejects a staging handle with this set.
 */
int32_t nominal_ingest_tabular_set_is_archive(int32_t staging, bool is_archive);

/*
 Frees a tabular-ingest staging handle. Freeing twice returns an error.
 */
int32_t nominal_ingest_tabular_free(int32_t staging);

/*
 Uploads a CSV file (`.csv` / `.csv.gz`) and ingests it into the existing
 dataset with the given RID, using the staged options (a timestamp spec is
 required). Blocks until the upload completes and the server accepts the
 ingest — the ingest itself continues server-side. Writes a job handle to
 `out_job`; poll it with `nominal_ingest_job_get`/`_wait`, read the target
 dataset back with `nominal_ingest_job_result_rid`, and free it with
 `nominal_ingest_job_free`. The staging handle stays valid for reuse.
 */
int32_t nominal_ingest_csv(int32_t client,
                           int32_t staging,
                           const char *file_path,
                           const char *dataset_rid,
                           int32_t *out_job);

/*
 Uploads a Parquet file (or archive of Parquet files — see
 `nominal_ingest_tabular_set_is_archive`) and ingests it into the existing
 dataset with the given RID. Otherwise identical to `nominal_ingest_csv`.
 */
int32_t nominal_ingest_parquet(int32_t client,
                               int32_t staging,
                               const char *file_path,
                               const char *dataset_rid,
                               int32_t *out_job);

/*
 Fetches the current state of the ingest job with the given RID, writing a
 job handle to `out_job` (free with `nominal_ingest_job_free`).
 */
int32_t nominal_ingest_job_get(int32_t client, const char *rid, int32_t *out_job);

/*
 Polls the ingest job with the given RID until it reaches a terminal state
 (Completed, Failed, Cancelled, or Unknown), then writes a job handle to
 `out_job`. BLOCKS the calling thread for as long as the job runs. A
 terminal-but-unsuccessful job is NOT an error here — check
 `nominal_ingest_job_status` on the returned handle. `poll_interval_ms`
 <= 0 uses the default (2000 ms).
 */
int32_t nominal_ingest_job_wait(int32_t client,
                                const char *rid,
                                double poll_interval_ms,
                                int32_t *out_job);

/*
 Writes the ingest job's RID into `buf`, storing the byte count needed in
 `out_needed`.
 */
int32_t nominal_ingest_job_rid(int32_t job, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Stores the job's status in `out_status` as a `NominalIngestJobStatus`
 value. This is a snapshot from when the handle was created — re-fetch
 with `nominal_ingest_job_get` for fresh state.
 */
int32_t nominal_ingest_job_status(int32_t job, int32_t *out_status);

/*
 Writes the RID of the dataset (or video) the ingest landed in into `buf`,
 and whether it is known into `is_present`. Only handles returned by the
 upload functions carry this; handles from `_get`/`_wait` report absent.
 */
int32_t nominal_ingest_job_result_rid(int32_t job,
                                      char *buf,
                                      uint32_t cap,
                                      uint32_t *out_needed,
                                      bool *is_present);

/*
 Frees an ingest-job handle. Freeing twice returns an error.
 */
int32_t nominal_ingest_job_free(int32_t job);

/*
 Creates a run with a name, start time (`f64` Unix milliseconds), optional
 description (null or empty = none), and optional end time (`has_end`
 false = still running / no end). Writes the new run's handle to
 `out_run`; free with `nominal_run_free`. For labels, properties, or asset
 links use the `nominal_run_create_begin` staging flow instead.
 */
int32_t nominal_run_create(int32_t client,
                           const char *name,
                           const char *description,
                           double start_ms,
                           double end_ms,
                           bool has_end,
                           int32_t *out_run);

/*
 Fetches the run with the given RID, writing its handle to `out_run`.
 Free with `nominal_run_free`.
 */
int32_t nominal_run_get(int32_t client, const char *rid, int32_t *out_run);

/*
 Lists all runs (newest first), returning a handle list.

 On success `*out_list` is a handle list of `*out_count` run handles —
 read them with `nominal_handle_list_get` and free the list with
 `nominal_handle_list_free`. Each run handle stays valid until passed to
 `nominal_run_free`, independent of the list.
 */
int32_t nominal_run_list(int32_t client, int32_t *out_list, uint32_t *out_count);

/*
 Searches runs, returning a handle list (see `nominal_run_list` for
 ownership).

 Filters are optional and combined with AND:
 - `search_text`, `label`, `property_key` + `property_value`: as in
   `nominal_asset_search` (null or empty = no filter)
 - `run_number`: 0 = no filter (real run numbers start at 1)
 - `start_after_ms` (with `has_start_after`): only runs starting at or
   after this Unix-millisecond timestamp
 - `end_before_ms` (with `has_end_before`): only runs ending at or before
   this Unix-millisecond timestamp
 */
int32_t nominal_run_search(int32_t client,
                           const char *search_text,
                           const char *label,
                           const char *property_key,
                           const char *property_value,
                           uint32_t run_number,
                           double start_after_ms,
                           bool has_start_after,
                           double end_before_ms,
                           bool has_end_before,
                           int32_t *out_list,
                           uint32_t *out_count);

/*
 Updates a run's name and/or description. Null or empty arguments leave
 that field unchanged. Writes a handle to the updated run to `out_run`
 (free with `nominal_run_free`). For labels, properties, or time changes
 use the `nominal_run_update_begin` staging flow instead.
 */
int32_t nominal_run_update(int32_t client,
                           const char *rid,
                           const char *name,
                           const char *description,
                           int32_t *out_run);

/*
 Attaches the dataset with `dataset_rid` to the run with `rid` under
 `ref_name`, writing a handle to the updated run to `out_run` (free with
 `nominal_run_free`).
 */
int32_t nominal_run_add_dataset(int32_t client,
                                const char *rid,
                                const char *ref_name,
                                const char *dataset_rid,
                                int32_t *out_run);

/*
 Attaches the video with `video_rid` to the run with `rid` under
 `ref_name`, writing a handle to the updated run to `out_run` (free with
 `nominal_run_free`).
 */
int32_t nominal_run_add_video(int32_t client,
                              const char *rid,
                              const char *ref_name,
                              const char *video_rid,
                              int32_t *out_run);

/*
 Attaches the connection with `connection_rid` to the run with `rid` under
 `ref_name`, writing a handle to the updated run to `out_run` (free with
 `nominal_run_free`).
 */
int32_t nominal_run_add_connection(int32_t client,
                                   const char *rid,
                                   const char *ref_name,
                                   const char *connection_rid,
                                   int32_t *out_run);

/*
 Archives a run (hidden from the UI, not deleted).
 */
int32_t nominal_run_archive(int32_t client, const char *rid);

/*
 Unarchives a run, restoring its visibility in the UI.
 */
int32_t nominal_run_unarchive(int32_t client, const char *rid);

/*
 Frees a run handle. Freeing twice returns an error.
 */
int32_t nominal_run_free(int32_t run);

/*
 Starts staging a run-create request with the required name and start time
 (`f64` Unix milliseconds). Add optional fields with the
 `nominal_run_create_set_*` / `_add_*` calls, then fire it with
 `nominal_run_create_commit`. Free with `nominal_run_create_free` (commit
 does not free).
 */
int32_t nominal_run_create_begin(const char *name, double start_ms, int32_t *out_staging);

/*
 Sets the description on a staged run create (empty clears it).
 */
int32_t nominal_run_create_set_description(int32_t staging, const char *description);

/*
 Sets the end time (`f64` Unix milliseconds) on a staged run create.
 */
int32_t nominal_run_create_set_end(int32_t staging, double end_ms);

/*
 Adds one label to a staged run create.
 */
int32_t nominal_run_create_add_label(int32_t staging, const char *label);

/*
 Sets one property on a staged run create (same key overwrites).
 */
int32_t nominal_run_create_set_property(int32_t staging, const char *key, const char *value);

/*
 Links one asset (by RID) to a staged run create.
 */
int32_t nominal_run_create_add_asset(int32_t staging, const char *asset_rid);

/*
 Creates the staged run, writing the new run's handle to `out_run` (free
 with `nominal_run_free`). The staging handle stays valid — free it with
 `nominal_run_create_free`.
 */
int32_t nominal_run_create_commit(int32_t client, int32_t staging, int32_t *out_run);

/*
 Frees a run-create staging handle. Freeing twice returns an error.
 */
int32_t nominal_run_create_free(int32_t staging);

/*
 Starts staging a run update. Only fields set via the
 `nominal_run_update_set_*` / `_add_*` calls are changed at commit; the
 rest remain untouched. Free with `nominal_run_update_free`.
 */
int32_t nominal_run_update_begin(int32_t *out_staging);

/*
 Stages a new name.
 */
int32_t nominal_run_update_set_name(int32_t staging, const char *name);

/*
 Stages a new description (empty clears the description).
 */
int32_t nominal_run_update_set_description(int32_t staging, const char *description);

/*
 Stages a new start time (`f64` Unix milliseconds).
 */
int32_t nominal_run_update_set_start(int32_t staging, double start_ms);

/*
 Stages a new end time (`f64` Unix milliseconds).
 */
int32_t nominal_run_update_set_end(int32_t staging, double end_ms);

/*
 Adds one label to the staged update. NOTE: touching labels at all means
 the commit REPLACES the run's entire label set with exactly the labels
 accumulated here (upstream semantics) — to keep existing labels, add them
 too.
 */
int32_t nominal_run_update_add_label(int32_t staging, const char *label);

/*
 Sets one property on the staged update (same key overwrites). NOTE: same
 replace semantics as labels — touching properties at all means the commit
 replaces the run's entire property map with the ones accumulated here.
 */
int32_t nominal_run_update_set_property(int32_t staging, const char *key, const char *value);

/*
 Applies the staged update to the run with the given RID, writing a handle
 to the updated run to `out_run` (free with `nominal_run_free`). At least
 one field must have been staged. The staging handle stays valid — free it
 with `nominal_run_update_free`.
 */
int32_t nominal_run_update_commit(int32_t client,
                                  const char *rid,
                                  int32_t staging,
                                  int32_t *out_run);

/*
 Frees a run-update staging handle. Freeing twice returns an error.
 */
int32_t nominal_run_update_free(int32_t staging);

/*
 Writes the run's RID into `buf`, storing the byte count needed in
 `out_needed`.
 */
int32_t nominal_run_rid(int32_t run, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Writes the run's name into `buf`, storing the byte count needed in
 `out_needed`.
 */
int32_t nominal_run_name(int32_t run, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Writes the run's description into `buf` (always present upstream — may be
 empty), storing the byte count needed in `out_needed`.
 */
int32_t nominal_run_description(int32_t run, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Writes the URL for viewing this run in the Nominal web app into `buf`,
 storing the byte count needed in `out_needed`.
 */
int32_t nominal_run_url(int32_t run, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Stores the run's number in `out_number`.
 */
int32_t nominal_run_number(int32_t run, uint32_t *out_number);

/*
 Writes the run's start time to `out_millis` as `f64` Unix milliseconds
 (UTC).
 */
int32_t nominal_run_start(int32_t run, double *out_millis);

/*
 Writes the run's end time to `out_millis` (`f64` Unix milliseconds, UTC)
 and whether one is set to `is_present` (an absent end — a still-running
 run — reports 0).
 */
int32_t nominal_run_end(int32_t run, double *out_millis, bool *is_present);

/*
 Writes the run's creation time to `out_millis` as `f64` Unix milliseconds
 (UTC).
 */
int32_t nominal_run_created_at(int32_t run, double *out_millis);

/*
 Stores the number of properties on the run in `out_count`.
 */
int32_t nominal_run_property_count(int32_t run, uint32_t *out_count);

/*
 Writes the key of the property at `index` (0-based, sorted-key order) into
 `buf`, storing the byte count needed in `out_needed`.
 */
int32_t nominal_run_property_key_at(int32_t run,
                                    int32_t index,
                                    char *buf,
                                    uint32_t cap,
                                    uint32_t *out_needed);

/*
 Writes the value of the property at `index` (0-based, sorted-key order)
 into `buf`, storing the byte count needed in `out_needed`.
 */
int32_t nominal_run_property_value_at(int32_t run,
                                      int32_t index,
                                      char *buf,
                                      uint32_t cap,
                                      uint32_t *out_needed);

/*
 Stores the number of labels on the run in `out_count`.
 */
int32_t nominal_run_label_count(int32_t run, uint32_t *out_count);

/*
 Writes the label at `index` (0-based) into `buf`, storing the byte count
 needed in `out_needed`.
 */
int32_t nominal_run_label_at(int32_t run,
                             int32_t index,
                             char *buf,
                             uint32_t cap,
                             uint32_t *out_needed);

/*
 Stores the number of assets linked to the run in `out_count`.
 */
int32_t nominal_run_asset_count(int32_t run, uint32_t *out_count);

/*
 Writes the RID of the linked asset at `index` (0-based) into `buf`,
 storing the byte count needed in `out_needed`. Fetch the full asset with
 `nominal_asset_get`.
 */
int32_t nominal_run_asset_rid_at(int32_t run,
                                 int32_t index,
                                 char *buf,
                                 uint32_t cap,
                                 uint32_t *out_needed);

/*
 Stores the number of data sources attached to the run in `out_count`.
 (Empty for multi-asset runs — data sources live on the assets there.)
 */
int32_t nominal_run_data_source_count(int32_t run, uint32_t *out_count);

/*
 Writes the ref name of the data source at `index` (0-based, sorted-name
 order) into `buf`, storing the byte count needed in `out_needed`.
 */
int32_t nominal_run_data_source_name_at(int32_t run,
                                        int32_t index,
                                        char *buf,
                                        uint32_t cap,
                                        uint32_t *out_needed);

/*
 Writes the RID of the data source at `index` (0-based, sorted-name order)
 into `buf`, storing the byte count needed in `out_needed`.
 */
int32_t nominal_run_data_source_rid_at(int32_t run,
                                       int32_t index,
                                       char *buf,
                                       uint32_t cap,
                                       uint32_t *out_needed);

/*
 Writes the kind of the data source at `index` (0-based, sorted-name order)
 to `out_type` as a `NominalDataSourceType` value.
 */
int32_t nominal_run_data_source_type_at(int32_t run, int32_t index, int32_t *out_type);

/*
 Fetches the template with the given RID (latest commit on the main
 branch), writing its handle to `out_template`. Free with
 `nominal_template_free`.
 */
int32_t nominal_template_get(int32_t client, const char *rid, int32_t *out_template);

/*
 Frees a template handle. Freeing twice returns an error.
 */
int32_t nominal_template_free(int32_t template_);

/*
 Writes the template's RID into `buf`, storing the byte count needed in
 `out_needed`.
 */
int32_t nominal_template_rid(int32_t template_, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Writes the template's title into `buf`, storing the byte count needed in
 `out_needed`.
 */
int32_t nominal_template_title(int32_t template_, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Writes the template's description into `buf`, and whether one is set into
 `is_present` (an absent description reports 0 bytes needed).
 */
int32_t nominal_template_description(int32_t template_,
                                     char *buf,
                                     uint32_t cap,
                                     uint32_t *out_needed,
                                     bool *is_present);

/*
 Writes the commit ID identifying this template version into `buf`,
 storing the byte count needed in `out_needed`.
 */
int32_t nominal_template_commit_id(int32_t template_,
                                   char *buf,
                                   uint32_t cap,
                                   uint32_t *out_needed);

/*
 Writes the URL for viewing this template in the Nominal web app into
 `buf`, storing the byte count needed in `out_needed`.
 */
int32_t nominal_template_url(int32_t template_, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Writes the template's creation time to `out_millis` as `f64` Unix
 milliseconds (UTC).
 */
int32_t nominal_template_created_at(int32_t template_, double *out_millis);

/*
 Fetches the authenticated user (the owner of the client's token),
 writing its handle to `out_user`. Free with `nominal_user_free`.
 */
int32_t nominal_user_me(int32_t client, int32_t *out_user);

/*
 Frees a user handle. Freeing twice returns an error.
 */
int32_t nominal_user_free(int32_t user);

/*
 Writes the user's RID into `buf`, storing the byte count needed in
 `out_needed`.
 */
int32_t nominal_user_rid(int32_t user, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Writes the RID of the user's organization into `buf`, storing the byte
 count needed in `out_needed`.
 */
int32_t nominal_user_org_rid(int32_t user, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Writes the user's email into `buf`, storing the byte count needed in
 `out_needed`.
 */
int32_t nominal_user_email(int32_t user, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Writes the user's display name into `buf`, storing the byte count needed
 in `out_needed`.
 */
int32_t nominal_user_display_name(int32_t user, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Creates an empty video (metadata shell — the media file arrives via
 ingest) with the given name and optional description, writing the new
 video's handle to `out_video`. Free with `nominal_video_free`. For labels
 or properties use the `nominal_video_create_begin` staging flow instead.
 */
int32_t nominal_video_create(int32_t client,
                             const char *name,
                             const char *description,
                             int32_t *out_video);

/*
 Fetches the video with the given RID, writing its handle to `out_video`.
 Free with `nominal_video_free`.
 */
int32_t nominal_video_get(int32_t client, const char *rid, int32_t *out_video);

/*
 Lists all videos (newest first), returning a handle list.

 On success `*out_list` is a handle list of `*out_count` video handles —
 read them with `nominal_handle_list_get` and free the list with
 `nominal_handle_list_free`. Each video handle stays valid until passed to
 `nominal_video_free`, independent of the list.
 */
int32_t nominal_video_list(int32_t client, int32_t *out_list, uint32_t *out_count);

/*
 Searches videos, returning a handle list (see `nominal_video_list` for
 ownership).

 Filters may each be null or empty ("no filter"); the ones provided are
 combined with AND:
 - `search_text`: fuzzy full-text match on name and description
 - `label`: exact label match
 - `property_key` + `property_value`: property match (both or neither)
 */
int32_t nominal_video_search(int32_t client,
                             const char *search_text,
                             const char *label,
                             const char *property_key,
                             const char *property_value,
                             int32_t *out_list,
                             uint32_t *out_count);

/*
 Updates a video's name and/or description. Null or empty arguments leave
 that field unchanged. Writes a handle to the updated video to `out_video`
 (free with `nominal_video_free`). For labels or properties use the
 `nominal_video_update_begin` staging flow instead.
 */
int32_t nominal_video_update(int32_t client,
                             const char *rid,
                             const char *name,
                             const char *description,
                             int32_t *out_video);

/*
 Archives a video (hidden from the UI, not deleted).
 */
int32_t nominal_video_archive(int32_t client, const char *rid);

/*
 Unarchives a video, restoring its visibility in the UI.
 */
int32_t nominal_video_unarchive(int32_t client, const char *rid);

/*
 Frees a video handle. Freeing twice returns an error.
 */
int32_t nominal_video_free(int32_t video);

/*
 Starts staging a video-create request with the (required) name. Add
 optional fields with the `nominal_video_create_set_*` / `_add_*` calls,
 then fire it with `nominal_video_create_commit`. Free with
 `nominal_video_create_free` (commit does not free).
 */
int32_t nominal_video_create_begin(const char *name, int32_t *out_staging);

/*
 Sets the description on a staged video create (empty clears it).
 */
int32_t nominal_video_create_set_description(int32_t staging, const char *description);

/*
 Adds one label to a staged video create.
 */
int32_t nominal_video_create_add_label(int32_t staging, const char *label);

/*
 Sets one property on a staged video create (same key overwrites).
 */
int32_t nominal_video_create_set_property(int32_t staging, const char *key, const char *value);

/*
 Creates the staged video, writing the new video's handle to `out_video`
 (free with `nominal_video_free`). The staging handle stays valid — free
 it with `nominal_video_create_free`.
 */
int32_t nominal_video_create_commit(int32_t client, int32_t staging, int32_t *out_video);

/*
 Frees a video-create staging handle. Freeing twice returns an error.
 */
int32_t nominal_video_create_free(int32_t staging);

/*
 Starts staging a video update. Only fields set via the
 `nominal_video_update_set_*` / `_add_*` calls are changed at commit; the
 rest remain untouched. Free with `nominal_video_update_free`.
 */
int32_t nominal_video_update_begin(int32_t *out_staging);

/*
 Stages a new name.
 */
int32_t nominal_video_update_set_name(int32_t staging, const char *name);

/*
 Stages a new description (empty clears the description).
 */
int32_t nominal_video_update_set_description(int32_t staging, const char *description);

/*
 Adds one label to the staged update. NOTE: touching labels at all means
 the commit REPLACES the video's entire label set with exactly the labels
 accumulated here (upstream semantics) — to keep existing labels, add them
 too.
 */
int32_t nominal_video_update_add_label(int32_t staging, const char *label);

/*
 Sets one property on the staged update (same key overwrites). NOTE: same
 replace semantics as labels — touching properties at all means the commit
 replaces the video's entire property map with the ones accumulated here.
 */
int32_t nominal_video_update_set_property(int32_t staging, const char *key, const char *value);

/*
 Applies the staged update to the video with the given RID, writing a
 handle to the updated video to `out_video` (free with
 `nominal_video_free`). At least one field must have been staged. The
 staging handle stays valid — free it with `nominal_video_update_free`.
 */
int32_t nominal_video_update_commit(int32_t client,
                                    const char *rid,
                                    int32_t staging,
                                    int32_t *out_video);

/*
 Frees a video-update staging handle. Freeing twice returns an error.
 */
int32_t nominal_video_update_free(int32_t staging);

/*
 Writes the video's RID into `buf`, storing the byte count needed in
 `out_needed`.
 */
int32_t nominal_video_rid(int32_t video, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Writes the video's name into `buf`, storing the byte count needed in
 `out_needed`.
 */
int32_t nominal_video_name(int32_t video, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Writes the video's description into `buf`, and whether one is set into
 `is_present` (an absent description reports 0 bytes needed).
 */
int32_t nominal_video_description(int32_t video,
                                  char *buf,
                                  uint32_t cap,
                                  uint32_t *out_needed,
                                  bool *is_present);

/*
 Writes the URL for viewing this video in the Nominal web app into `buf`,
 storing the byte count needed in `out_needed`.
 */
int32_t nominal_video_url(int32_t video, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Writes the video's creation time to `out_millis` as `f64` Unix
 milliseconds (UTC).
 */
int32_t nominal_video_created_at(int32_t video, double *out_millis);

/*
 Stores the number of properties on the video in `out_count`.
 */
int32_t nominal_video_property_count(int32_t video, uint32_t *out_count);

/*
 Writes the key of the property at `index` (0-based, sorted-key order)
 into `buf`, storing the byte count needed in `out_needed`.
 */
int32_t nominal_video_property_key_at(int32_t video,
                                      int32_t index,
                                      char *buf,
                                      uint32_t cap,
                                      uint32_t *out_needed);

/*
 Writes the value of the property at `index` (0-based, sorted-key order)
 into `buf`, storing the byte count needed in `out_needed`.
 */
int32_t nominal_video_property_value_at(int32_t video,
                                        int32_t index,
                                        char *buf,
                                        uint32_t cap,
                                        uint32_t *out_needed);

/*
 Stores the number of labels on the video in `out_count`.
 */
int32_t nominal_video_label_count(int32_t video, uint32_t *out_count);

/*
 Writes the label at `index` (0-based) into `buf`, storing the byte count
 needed in `out_needed`.
 */
int32_t nominal_video_label_at(int32_t video,
                               int32_t index,
                               char *buf,
                               uint32_t cap,
                               uint32_t *out_needed);

/*
 Fetches the workbook with the given RID, writing its handle to
 `out_workbook`. Free with `nominal_workbook_free`.
 */
int32_t nominal_workbook_get(int32_t client, const char *rid, int32_t *out_workbook);

/*
 Lists all workbooks (search with no filters), returning a handle list.

 On success `*out_list` is a handle list of `*out_count` workbook handles —
 read them with `nominal_handle_list_get` and free the list with
 `nominal_handle_list_free`. Each workbook handle stays valid until passed
 to `nominal_workbook_free`, independent of the list.
 */
int32_t nominal_workbook_list(int32_t client, int32_t *out_list, uint32_t *out_count);

/*
 Searches workbooks, returning a handle list (see `nominal_workbook_list`
 for ownership).

 Filters may each be null or empty ("no filter"); the ones provided are
 combined with AND:
 - `search_text`: fuzzy full-text match on title and description
 - `label`: exact label match
 - `property_key` + `property_value`: property match (both or neither)
 - `asset_rid`: workbooks attached to this asset
 - `run_rid`: workbooks attached to this run
 */
int32_t nominal_workbook_search(int32_t client,
                                const char *search_text,
                                const char *label,
                                const char *property_key,
                                const char *property_value,
                                const char *asset_rid,
                                const char *run_rid,
                                int32_t *out_list,
                                uint32_t *out_count);

/*
 Archives a workbook (hidden from the UI, not deleted).
 */
int32_t nominal_workbook_archive(int32_t client, const char *rid);

/*
 Unarchives a workbook, restoring its visibility in the UI.
 */
int32_t nominal_workbook_unarchive(int32_t client, const char *rid);

/*
 Frees a workbook handle. Freeing twice returns an error.
 */
int32_t nominal_workbook_free(int32_t workbook);

/*
 Starts staging a workbook-create request. Add at least one scope RID
 (`nominal_workbook_create_add_scope_asset` or `_add_scope_run` — not
 both), optionally override title/description (they default to the
 template's), then fire it with `nominal_workbook_create_commit`. Free
 with `nominal_workbook_create_free` (commit does not free).
 */
int32_t nominal_workbook_create_begin(int32_t *out_staging);

/*
 Sets the workbook's title (overrides the template's).
 */
int32_t nominal_workbook_create_set_title(int32_t staging, const char *title);

/*
 Sets the workbook's description (overrides the template's).
 */
int32_t nominal_workbook_create_set_description(int32_t staging, const char *description);

/*
 Adds one label to the staged create.
 */
int32_t nominal_workbook_create_add_label(int32_t staging, const char *label);

/*
 Sets one property on the staged create (same key overwrites).
 */
int32_t nominal_workbook_create_set_property(int32_t staging, const char *key, const char *value);

/*
 Adds an asset RID to the workbook's data scope. Mutually exclusive with
 `nominal_workbook_create_add_scope_run`.
 */
int32_t nominal_workbook_create_add_scope_asset(int32_t staging, const char *asset_rid);

/*
 Adds a run RID to the workbook's data scope. Mutually exclusive with
 `nominal_workbook_create_add_scope_asset`.
 */
int32_t nominal_workbook_create_add_scope_run(int32_t staging, const char *run_rid);

/*
 Creates the staged workbook from the given template (see
 `nominal_template_get`), writing the new workbook's handle to
 `out_workbook` (free with `nominal_workbook_free`). At least one scope
 RID must have been staged. The staging handle stays valid — free it with
 `nominal_workbook_create_free`.
 */
int32_t nominal_workbook_create_commit(int32_t client,
                                       int32_t template_,
                                       int32_t staging,
                                       int32_t *out_workbook);

/*
 Frees a workbook-create staging handle. Freeing twice returns an error.
 */
int32_t nominal_workbook_create_free(int32_t staging);

/*
 Writes the workbook's RID into `buf`, storing the byte count needed in
 `out_needed`.
 */
int32_t nominal_workbook_rid(int32_t workbook, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Writes the workbook's name into `buf`, storing the byte count needed in
 `out_needed`.
 */
int32_t nominal_workbook_name(int32_t workbook, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Writes the workbook's description into `buf`, and whether one is set into
 `is_present` (an absent description reports 0 bytes needed).
 */
int32_t nominal_workbook_description(int32_t workbook,
                                     char *buf,
                                     uint32_t cap,
                                     uint32_t *out_needed,
                                     bool *is_present);

/*
 Writes the URL for viewing this workbook in the Nominal web app into
 `buf`, storing the byte count needed in `out_needed`.
 */
int32_t nominal_workbook_url(int32_t workbook, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Writes the workbook's creation time to `out_millis` as `f64` Unix
 milliseconds (UTC).
 */
int32_t nominal_workbook_created_at(int32_t workbook, double *out_millis);

/*
 Stores whether the workbook's scope is assets (0) or runs (1) in
 `out_type`, as a `NominalWorkbookScopeType` value.
 */
int32_t nominal_workbook_scope_type(int32_t workbook, int32_t *out_type);

/*
 Stores the number of RIDs in the workbook's data scope in `out_count`.
 */
int32_t nominal_workbook_scope_rid_count(int32_t workbook, uint32_t *out_count);

/*
 Writes the scope RID at `index` (0-based) into `buf`, storing the byte
 count needed in `out_needed`. Whether they are asset or run RIDs is
 reported by `nominal_workbook_scope_type`.
 */
int32_t nominal_workbook_scope_rid_at(int32_t workbook,
                                      int32_t index,
                                      char *buf,
                                      uint32_t cap,
                                      uint32_t *out_needed);

/*
 Stores the number of properties on the workbook in `out_count`.
 */
int32_t nominal_workbook_property_count(int32_t workbook, uint32_t *out_count);

/*
 Writes the key of the property at `index` (0-based, sorted-key order)
 into `buf`, storing the byte count needed in `out_needed`.
 */
int32_t nominal_workbook_property_key_at(int32_t workbook,
                                         int32_t index,
                                         char *buf,
                                         uint32_t cap,
                                         uint32_t *out_needed);

/*
 Writes the value of the property at `index` (0-based, sorted-key order)
 into `buf`, storing the byte count needed in `out_needed`.
 */
int32_t nominal_workbook_property_value_at(int32_t workbook,
                                           int32_t index,
                                           char *buf,
                                           uint32_t cap,
                                           uint32_t *out_needed);

/*
 Stores the number of labels on the workbook in `out_count`.
 */
int32_t nominal_workbook_label_count(int32_t workbook, uint32_t *out_count);

/*
 Writes the label at `index` (0-based) into `buf`, storing the byte count
 needed in `out_needed`.
 */
int32_t nominal_workbook_label_at(int32_t workbook,
                                  int32_t index,
                                  char *buf,
                                  uint32_t cap,
                                  uint32_t *out_needed);

/*
 Lists the workspaces the authenticated user can access (sorted by display
 name), returning a handle list.

 On success `*out_list` is a handle list of `*out_count` workspace handles
 — read them with `nominal_handle_list_get` and free the list with
 `nominal_handle_list_free`. Each workspace handle stays valid until
 passed to `nominal_workspace_free`, independent of the list.
 */
int32_t nominal_workspace_list(int32_t client, int32_t *out_list, uint32_t *out_count);

/*
 Frees a workspace handle. Freeing twice returns an error.
 */
int32_t nominal_workspace_free(int32_t workspace);

/*
 Writes the workspace's RID into `buf`, storing the byte count needed in
 `out_needed`. This is the value `nominal_client_new` takes as
 `workspace_rid`.
 */
int32_t nominal_workspace_rid(int32_t workspace, char *buf, uint32_t cap, uint32_t *out_needed);

/*
 Writes the workspace's display name into `buf`, and whether one is set
 into `is_present` (an absent name reports 0 bytes needed).
 */
int32_t nominal_workspace_display_name(int32_t workspace,
                                       char *buf,
                                       uint32_t cap,
                                       uint32_t *out_needed,
                                       bool *is_present);

#endif  /* NOMINAL_FFI_H */
